export const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
export const uid=()=>globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;

const makeCanvas=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
const cloneCanvas=src=>{const c=makeCanvas(src.width,src.height);c.getContext('2d').drawImage(src,0,0);return c};
const VISUAL_TYPES=new Set(['raster','smart','text','shape','tiled']);
export const defaultAdjustments=()=>({brightness:0,contrast:0,saturation:0,blackPoint:0,gamma:1,whitePoint:255,curve:[0,64,128,192,255],curves:{rgb:[0,64,128,192,255],r:[0,64,128,192,255],g:[0,64,128,192,255],b:[0,64,128,192,255]}});
export const defaultLayerFx=()=>({enabled:false,shadow:false,shadowColor:'#000000',shadowOpacity:.55,shadowBlur:18,shadowX:8,shadowY:10,glow:false,glowColor:'#7c5cff',glowOpacity:.55,glowBlur:20,stroke:false,strokeColor:'#ffffff',strokeSize:2});
export const defaultTextStyle=()=>({content:'Texto',fontFamily:'system-ui',fontSize:72,fontWeight:700,fontStyle:'normal',color:'#f5f7ff',align:'left',lineHeight:1.15,letterSpacing:0});
export const defaultShapeStyle=()=>({kind:'rect',x:120,y:120,width:360,height:240,radius:24,fill:'#7c5cff',stroke:'#f5f7ff',strokeWidth:3,points:[]});
export const identityWarp=(w=1,h=1)=>[{x:0,y:0},{x:w,y:0},{x:w,y:h},{x:0,y:h}];
export const identityWarpMesh=(w=1,h=1,cols=3,rows=3)=>({cols,rows,points:Array.from({length:cols*rows},(_,i)=>{const x=i%cols,y=Math.floor(i/cols);return{x:x/(cols-1)*w,y:y/(rows-1)*h}})});

function baseLayer(type,name){return{id:uid(),type,name,parentId:null,visible:true,locked:false,opacity:1,blend:'source-over',x:0,y:0,scaleX:1,scaleY:1,rotation:0,mask:null,fx:defaultLayerFx()}}

export class PixelDocument{
  constructor(width=1200,height=800,bg='transparent',initialize=true){
    this.width=width;this.height=height;this.layers=[];this.activeLayerId=null;this.name='Sin título';
    this.guides={vertical:[],horizontal:[]};this.grid={enabled:false,size:50,snap:true};
    if(initialize)this.addLayer('Fondo',bg);
  }
  createCanvas(){return makeCanvas(this.width,this.height)}
  makeRasterLayer(name=`Capa ${this.layers.length+1}`,fill='transparent'){
    const canvas=this.createCanvas(),ctx=canvas.getContext('2d',{willReadFrequently:true});
    if(fill!=='transparent'){ctx.fillStyle=fill;ctx.fillRect(0,0,this.width,this.height)}
    return {...baseLayer('raster',name),canvas};
  }
  addLayer(name=`Capa ${this.layers.length+1}`,fill='transparent',parentId=null){const layer=this.makeRasterLayer(name,fill);layer.parentId=parentId;this.layers.push(layer);this.activeLayerId=layer.id;return layer}
  addSmartLayer(name='Smart Layer',canvas=null,parentId=null){const layer={...baseLayer('smart',name),canvas:canvas?cloneCanvas(canvas):this.createCanvas(),smart:{sourceName:name,createdAt:Date.now()}};layer.parentId=parentId;this.layers.push(layer);this.activeLayerId=layer.id;return layer}
  addTextLayer(name='Texto',text={},position={x:0,y:0},parentId=null){const layer={...baseLayer('text',name),canvas:null,text:{...defaultTextStyle(),...text}};layer.parentId=parentId;layer.x=Number(position.x)||0;layer.y=Number(position.y)||0;this.layers.push(layer);this.activeLayerId=layer.id;return layer}
  addShapeLayer(name='Forma',shape={},parentId=null){const layer={...baseLayer('shape',name),canvas:null,shape:{...defaultShapeStyle(),...shape}};layer.parentId=parentId;this.layers.push(layer);this.activeLayerId=layer.id;return layer}
  addTiledLayer(name='Tiled Layer',tiled={},parentId=null){const layer={...baseLayer('tiled',name),canvas:null,tiled:{tileSize:512,width:this.width,height:this.height,tiles:[],...tiled}};layer.parentId=parentId;this.layers.push(layer);this.activeLayerId=layer.id;return layer}
  addGroup(name='Grupo',parentId=null){const layer={...baseLayer('group',name),canvas:null,expanded:true};layer.parentId=parentId;this.layers.push(layer);this.activeLayerId=layer.id;return layer}
  addAdjustmentLayer(name='Ajuste',adjustments={},parentId=null){const layer={...baseLayer('adjustment',name),canvas:null,adjustments:normalizeAdjustments(adjustments)};layer.parentId=parentId;this.layers.push(layer);this.activeLayerId=layer.id;return layer}
  get activeLayer(){return this.layers.find(l=>l.id===this.activeLayerId)||this.layers.at(-1)}
  childrenOf(parentId=null){return this.layers.filter(l=>(l.parentId??null)===(parentId??null))}
  descendantsOf(id){const result=[];const walk=pid=>{for(const l of this.childrenOf(pid)){result.push(l);if(l.type==='group')walk(l.id)}};walk(id);return result}
  removeLayer(id=this.activeLayerId){if(this.layers.length<=1)return false;const i=this.layers.findIndex(l=>l.id===id);if(i<0)return false;const layer=this.layers[i];if(layer.type==='group'){for(const child of this.childrenOf(layer.id))child.parentId=layer.parentId??null}this.layers.splice(i,1);this.activeLayerId=this.layers[Math.max(0,i-1)]?.id||this.layers.at(-1)?.id;return true}
  duplicateLayer(id=this.activeLayerId){
    const src=this.layers.find(l=>l.id===id);if(!src)return null;const idMap=new Map();
    const cloneOne=s=>{const n=cloneLayerData(s);n.id=uid();n.name=`${s.name} copia`;idMap.set(s.id,n.id);return n};
    const clones=[cloneOne(src)];if(src.type==='group')for(const d of this.descendantsOf(src.id))clones.push(cloneOne(d));
    for(const c of clones){const original=[src,...this.descendantsOf(src.id)].find(x=>idMap.get(x.id)===c.id);if(original?.parentId&&idMap.has(original.parentId))c.parentId=idMap.get(original.parentId)}
    const subtreeIds=new Set([src.id,...this.descendantsOf(src.id).map(x=>x.id)]);let insertAt=Math.max(...[...subtreeIds].map(x=>this.layers.findIndex(l=>l.id===x)))+1;this.layers.splice(insertAt,0,...clones);this.activeLayerId=clones[0].id;return clones[0]
  }
  addMask(id=this.activeLayerId,fill='white'){const layer=this.layers.find(l=>l.id===id);if(!layer||!VISUAL_TYPES.has(layer.type))return false;const mask=this.createCanvas(),ctx=mask.getContext('2d',{willReadFrequently:true});if(fill==='white'){ctx.fillStyle='#fff';ctx.fillRect(0,0,this.width,this.height)}layer.mask=mask;return true}
  removeMask(id=this.activeLayerId){const l=this.layers.find(x=>x.id===id);if(!l?.mask)return false;l.mask=null;return true}
  convertToSmart(id=this.activeLayerId){const l=this.layers.find(x=>x.id===id);if(!l||l.type!=='raster')return false;l.type='smart';l.smart={sourceName:l.name,createdAt:Date.now()};return true}
  rasterize(id=this.activeLayerId){const l=this.layers.find(x=>x.id===id);if(!l||!VISUAL_TYPES.has(l.type)||l.type==='raster')return false;const rendered=this.renderLayer(l);l.type='raster';l.canvas=rendered;l.text=undefined;l.smart=undefined;l.mask=null;l.fx=defaultLayerFx();l.x=l.y=l.rotation=0;l.scaleX=l.scaleY=1;return true}
  composite(target){const ctx=target.getContext('2d');ctx.clearRect(0,0,target.width,target.height);this.#compositeLevel(target,null)}
  #compositeLevel(target,parentId){for(const layer of this.childrenOf(parentId)){if(!layer.visible)continue;if(layer.type==='group'){const groupCanvas=makeCanvas(target.width,target.height);this.#compositeLevel(groupCanvas,layer.id);const tctx=target.getContext('2d');tctx.save();tctx.globalAlpha=layer.opacity;tctx.globalCompositeOperation=layer.blend;tctx.drawImage(groupCanvas,0,0);tctx.restore();continue}if(layer.type==='adjustment'){this.#applyAdjustmentComposite(target,layer);continue}const rendered=this.renderLayer(layer);const tctx=target.getContext('2d');tctx.save();tctx.globalAlpha=layer.opacity;tctx.globalCompositeOperation=layer.blend;tctx.drawImage(rendered,0,0);tctx.restore()}}
  compositeRegion(target,region={x:0,y:0,w:this.width,h:this.height}){const r=normalizeRegion(region,this.width,this.height),ctx=target.getContext('2d');ctx.clearRect(0,0,target.width,target.height);this.#compositeRegionLevel(target,null,r)}
  #compositeRegionLevel(target,parentId,region){for(const layer of this.childrenOf(parentId)){if(!layer.visible)continue;if(layer.type==='group'){const groupCanvas=makeCanvas(target.width,target.height);this.#compositeRegionLevel(groupCanvas,layer.id,region);const tctx=target.getContext('2d');tctx.save();tctx.globalAlpha=layer.opacity;tctx.globalCompositeOperation=layer.blend;tctx.drawImage(groupCanvas,0,0);tctx.restore();continue}if(layer.type==='adjustment'){applyAdjustmentToSizedComposite(target,layer);continue}const rendered=renderLayerRegionCanvas(this,layer,region,target.width,target.height),tctx=target.getContext('2d');tctx.save();tctx.globalAlpha=layer.opacity;tctx.globalCompositeOperation=layer.blend;tctx.drawImage(rendered,0,0);tctx.restore()}}
  renderLayerSource(layer){if(layer.type==='text')return renderTextCanvas(layer,this.width,this.height);if(layer.type==='shape')return renderShapeCanvas(layer,this.width,this.height);if(layer.type==='tiled')return renderTiledCanvas(layer,this.width,this.height);if(layer.canvas)return cloneCanvas(layer.canvas);return this.createCanvas()}
  renderLayerThumbnail(layer,maxW=84,maxH=64){return renderLayerRegionCanvas(this,layer,{x:0,y:0,w:this.width,h:this.height},maxW,maxH,{thumbnail:true})}
  renderLayerRegion(layer,region,outW=Math.max(1,Math.round(region.w)),outH=Math.max(1,Math.round(region.h))){return renderLayerRegionCanvas(this,layer,normalizeRegion(region,this.width,this.height),outW,outH)}
  renderLayer(layer){let source=this.renderLayerSource(layer);if(layer.warpMesh?.points?.length>=4)source=warpCanvasMesh(source,layer.warpMesh,this.width,this.height);else if(layer.warp?.length===4)source=warpCanvasToQuad(source,layer.warp,this.width,this.height,Math.max(8,Number(layer.warpGrid)||18));const out=this.createCanvas(),ctx=out.getContext('2d');drawLayerTransformed(ctx,source,layer,this.width,this.height);if(layer.mask){let maskSource=layer.mask;if(layer.warpMesh?.points?.length>=4)maskSource=warpCanvasMesh(maskSource,layer.warpMesh,this.width,this.height);else if(layer.warp?.length===4)maskSource=warpCanvasToQuad(maskSource,layer.warp,this.width,this.height,Math.max(8,Number(layer.warpGrid)||18));const mask=this.createCanvas(),mctx=mask.getContext('2d');drawLayerTransformed(mctx,maskSource,layer,this.width,this.height);ctx.save();ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0);ctx.restore()}return applyLayerEffects(out,layer.fx,this.width,this.height)}
  #applyAdjustmentComposite(target,layer){applyAdjustmentToSizedComposite(target,layer)}
  resize(width,height){const oldW=this.width,oldH=this.height;this.width=width;this.height=height;for(const l of this.layers){if(l.canvas){const c=makeCanvas(width,height);c.getContext('2d').drawImage(l.canvas,0,0,oldW,oldH,0,0,oldW,oldH);l.canvas=c}if(l.mask){const m=makeCanvas(width,height);m.getContext('2d').drawImage(l.mask,0,0,oldW,oldH,0,0,oldW,oldH);l.mask=m}}this.guides.vertical=this.guides.vertical.filter(x=>x<=width);this.guides.horizontal=this.guides.horizontal.filter(y=>y<=height)}
  async snapshot(){return{width:this.width,height:this.height,name:this.name,activeLayerId:this.activeLayerId,guides:this.guides,grid:this.grid,layers:await Promise.all(this.layers.map(async l=>{const tiled=l.tiled?{...l.tiled,tiles:await Promise.all((l.tiled.tiles||[]).map(async t=>({x:t.x,y:t.y,w:t.w,h:t.h,dataURL:t.canvas?(t._dataURLCache||(t._dataURLCache=await canvasToDataURL(t.canvas))):t.dataURL||null})))}:undefined;return{...l,fx:{...defaultLayerFx(),...l.fx},text:l.text?{...defaultTextStyle(),...l.text}:undefined,shape:l.shape?{...defaultShapeStyle(),...l.shape}:undefined,tiled,adjustments:l.adjustments?normalizeAdjustments(l.adjustments):undefined,canvas:l.canvas?await canvasToDataURL(l.canvas):null,mask:l.mask?await canvasToDataURL(l.mask):null}}))}}
  static async fromSnapshot(data){if(!data||!Number.isInteger(data.width)||!Number.isInteger(data.height)||!Array.isArray(data.layers))throw new Error('Snapshot inválido');if(data.width<1||data.height<1||data.width>300000||data.height>300000||data.width*data.height>120_000_000)throw new Error('Documento fuera de los límites seguros');if(data.layers.length>1000)throw new Error('Demasiadas capas en el proyecto');const doc=new PixelDocument(data.width,data.height,'transparent',false);doc.name=String(data.name||'Proyecto').slice(0,160);doc.activeLayerId=data.activeLayerId;doc.guides={vertical:[...(data.guides?.vertical||[])],horizontal:[...(data.guides?.horizontal||[])]};doc.grid={enabled:!!data.grid?.enabled,size:clamp(Number(data.grid?.size)||50,4,500),snap:data.grid?.snap!==false};doc.layers=[];for(const raw of data.layers){const type=raw.type||'raster';let canvas=null,mask=null,tiled=raw.tiled?{...raw.tiled,tiles:[]}:undefined;if(['raster','smart'].includes(type)){canvas=makeCanvas(doc.width,doc.height);if(raw.canvas)await drawDataURL(canvas,raw.canvas)}if(type==='tiled'&&raw.tiled){for(const rt of raw.tiled.tiles||[]){const c=makeCanvas(rt.w||raw.tiled.tileSize||512,rt.h||raw.tiled.tileSize||512);if(rt.dataURL)await drawDataURL(c,rt.dataURL);tiled.tiles.push({...rt,canvas:c})}}if(raw.mask){mask=makeCanvas(doc.width,doc.height);await drawDataURL(mask,raw.mask)}doc.layers.push({...raw,type,parentId:raw.parentId??null,canvas,mask,tiled,scaleX:Number.isFinite(raw.scaleX)?raw.scaleX:1,scaleY:Number.isFinite(raw.scaleY)?raw.scaleY:1,rotation:Number.isFinite(raw.rotation)?raw.rotation:0,x:Number.isFinite(raw.x)?raw.x:0,y:Number.isFinite(raw.y)?raw.y:0,fx:{...defaultLayerFx(),...raw.fx},text:type==='text'?{...defaultTextStyle(),...raw.text}:undefined,shape:type==='shape'?{...defaultShapeStyle(),...raw.shape}:undefined,adjustments:type==='adjustment'?normalizeAdjustments(raw.adjustments):undefined})}if(!doc.layers.length)doc.addLayer('Fondo','transparent');if(!doc.layers.some(l=>l.id===doc.activeLayerId))doc.activeLayerId=doc.layers.at(-1)?.id;return doc}
}


function normalizeRegion(region,w,h){const x=Number(region?.x)||0,y=Number(region?.y)||0,rw=Math.max(1,Number(region?.w)||w),rh=Math.max(1,Number(region?.h)||h);return{x,y,w:rw,h:rh}}
function setRegionTransform(ctx,region,outW,outH){const sx=outW/region.w,sy=outH/region.h;ctx.setTransform(sx,0,0,sy,-region.x*sx,-region.y*sy)}
function applyLayerTransformToContext(ctx,layer,w,h){ctx.translate(w/2+(layer.x||0),h/2+(layer.y||0));ctx.rotate(layer.rotation||0);ctx.scale(layer.scaleX||1,layer.scaleY||1);ctx.translate(-w/2,-h/2)}
function regionInLayerSpace(region,layer,w,h){const pts=[{x:region.x,y:region.y},{x:region.x+region.w,y:region.y},{x:region.x+region.w,y:region.y+region.h},{x:region.x,y:region.y+region.h}].map(p=>layerPointFromDocument(p,layer,w,h));return{x:Math.min(...pts.map(p=>p.x)),y:Math.min(...pts.map(p=>p.y)),r:Math.max(...pts.map(p=>p.x)),b:Math.max(...pts.map(p=>p.y))}}
function drawShapePath(ctx,s){ctx.beginPath();if(s.kind==='ellipse')ctx.ellipse(s.x+s.width/2,s.y+s.height/2,Math.abs(s.width/2),Math.abs(s.height/2),0,0,Math.PI*2);else if(s.kind==='line'){ctx.moveTo(s.x,s.y);ctx.lineTo(s.x+s.width,s.y+s.height)}else if(s.kind==='polygon'&&Array.isArray(s.points)&&s.points.length>1){ctx.moveTo(s.points[0].x,s.points[0].y);for(const p of s.points.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath()}else{const r=Math.max(0,Math.min(Number(s.radius)||0,Math.abs(s.width)/2,Math.abs(s.height)/2));if(ctx.roundRect)ctx.roundRect(s.x,s.y,s.width,s.height,r);else ctx.rect(s.x,s.y,s.width,s.height)}}
function drawShapeDirect(ctx,layer){const s={...defaultShapeStyle(),...layer.shape};ctx.save();ctx.fillStyle=s.fill||'transparent';ctx.strokeStyle=s.stroke||'transparent';ctx.lineWidth=Math.max(0,Number(s.strokeWidth)||0);drawShapePath(ctx,s);if(s.kind!=='line'&&s.fill&&s.fill!=='transparent')ctx.fill();if(s.strokeWidth>0&&s.stroke&&s.stroke!=='transparent')ctx.stroke();ctx.restore()}
function drawTextDirect(ctx,layer){const t={...defaultTextStyle(),...layer.text};ctx.save();ctx.fillStyle=t.color;ctx.textBaseline='top';ctx.textAlign=t.align;ctx.font=`${t.fontStyle} ${t.fontWeight} ${Math.max(4,t.fontSize)}px ${safeFont(t.fontFamily)}`;const lines=String(t.content??'').split('\n'),measure=line=>ctx.measureText(line).width+Math.max(0,line.length-1)*(t.letterSpacing||0),maxWidth=Math.max(1,...lines.map(measure)),x=t.align==='center'?maxWidth/2:t.align==='right'?maxWidth:0;let y=0;for(const line of lines){if(t.letterSpacing)drawSpacedText(ctx,line,x,y,t.letterSpacing,t.align);else ctx.fillText(line,x,y);y+=t.fontSize*t.lineHeight}ctx.restore()}
function drawTiledDirect(ctx,layer,localRegion=null){for(const tile of layer.tiled?.tiles||[]){if(localRegion&&(tile.x+tile.w<localRegion.x||tile.y+tile.h<localRegion.y||tile.x>localRegion.r||tile.y>localRegion.b))continue;if(tile.canvas)ctx.drawImage(tile.canvas,tile.x,tile.y);else if(tile._img?.complete)ctx.drawImage(tile._img,tile.x,tile.y)}}
function drawLayerDirectRegion(ctx,doc,layer,region,outW,outH){ctx.save();setRegionTransform(ctx,region,outW,outH);applyLayerTransformToContext(ctx,layer,doc.width,doc.height);if(layer.type==='tiled')drawTiledDirect(ctx,layer,regionInLayerSpace(region,layer,doc.width,doc.height));else if(layer.type==='text')drawTextDirect(ctx,layer);else if(layer.type==='shape')drawShapeDirect(ctx,layer);else if(layer.canvas)ctx.drawImage(layer.canvas,0,0);ctx.restore()}
function renderLayerRegionCanvas(doc,layer,region,outW,outH,options={}){const out=makeCanvas(outW,outH);if(layer.warpMesh?.points?.length>=4||layer.warp?.length===4){const full=doc.renderLayer(layer),ctx=out.getContext('2d');ctx.drawImage(full,region.x,region.y,region.w,region.h,0,0,outW,outH);return out}drawLayerDirectRegion(out.getContext('2d'),doc,layer,region,outW,outH);if(layer.mask){const mask=makeCanvas(outW,outH),mctx=mask.getContext('2d');mctx.save();setRegionTransform(mctx,region,outW,outH);applyLayerTransformToContext(mctx,layer,doc.width,doc.height);mctx.drawImage(layer.mask,0,0);mctx.restore();const ctx=out.getContext('2d');ctx.save();ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0);ctx.restore()}return applyLayerEffects(out,layer.fx,outW,outH)}
function applyAdjustmentToSizedComposite(target,layer){const source=cloneCanvas(target),adjusted=makeCanvas(target.width,target.height),actx=adjusted.getContext('2d');actx.filter=adjustmentFilter(layer.adjustments);actx.drawImage(source,0,0);actx.filter='none';applyToneControls(adjusted,layer.adjustments);const tctx=target.getContext('2d');if(layer.opacity>=.999&&layer.blend==='source-over'){tctx.clearRect(0,0,target.width,target.height);tctx.drawImage(adjusted,0,0);return}tctx.save();tctx.globalAlpha=layer.opacity;tctx.globalCompositeOperation=layer.blend;tctx.drawImage(adjusted,0,0);tctx.restore()}

function cloneLayerData(src){return{...src,fx:{...defaultLayerFx(),...src.fx},text:src.text?{...src.text}:undefined,shape:src.shape?{...src.shape,points:Array.isArray(src.shape.points)?src.shape.points.map(p=>({...p})):[]}:undefined,smart:src.smart?{...src.smart}:undefined,tiled:src.tiled?{...src.tiled,tiles:(src.tiled.tiles||[]).map(t=>({...t,canvas:t.canvas?cloneCanvas(t.canvas):null}))}:undefined,adjustments:src.adjustments?normalizeAdjustments(src.adjustments):undefined,canvas:src.canvas?cloneCanvas(src.canvas):null,mask:src.mask?cloneCanvas(src.mask):null}}
function normalizeCurves(curves,legacy){const lin=[0,64,128,192,255],src=curves||{};return{rgb:normalizeCurve(src.rgb||legacy||lin),r:normalizeCurve(src.r||lin),g:normalizeCurve(src.g||lin),b:normalizeCurve(src.b||lin)}}
function normalizeAdjustments(a={}){const base=defaultAdjustments();return{...base,...a,curve:normalizeCurve(a.curve),curves:normalizeCurves(a.curves,a.curve)}}
function renderShapeCanvas(layer,w,h){const c=makeCanvas(w,h),ctx=c.getContext('2d'),s={...defaultShapeStyle(),...layer.shape};ctx.save();ctx.fillStyle=s.fill||'transparent';ctx.strokeStyle=s.stroke||'transparent';ctx.lineWidth=Math.max(0,Number(s.strokeWidth)||0);ctx.beginPath();if(s.kind==='ellipse')ctx.ellipse(s.x+s.width/2,s.y+s.height/2,Math.abs(s.width/2),Math.abs(s.height/2),0,0,Math.PI*2);else if(s.kind==='line'){ctx.moveTo(s.x,s.y);ctx.lineTo(s.x+s.width,s.y+s.height)}else if(s.kind==='polygon'&&Array.isArray(s.points)&&s.points.length>1){ctx.moveTo(s.points[0].x,s.points[0].y);for(const p of s.points.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath()}else{const r=Math.max(0,Math.min(Number(s.radius)||0,Math.abs(s.width)/2,Math.abs(s.height)/2));if(ctx.roundRect)ctx.roundRect(s.x,s.y,s.width,s.height,r);else ctx.rect(s.x,s.y,s.width,s.height)}if(s.kind!=='line'&&s.fill&&s.fill!=='transparent')ctx.fill();if(s.strokeWidth>0&&s.stroke&&s.stroke!=='transparent')ctx.stroke();ctx.restore();return c}
function renderTiledCanvas(layer,w,h){const c=makeCanvas(w,h),ctx=c.getContext('2d');for(const tile of layer.tiled?.tiles||[]){if(tile.canvas)ctx.drawImage(tile.canvas,tile.x,tile.y);else if(tile.dataURL){const img=tile._img;if(img?.complete)ctx.drawImage(img,tile.x,tile.y)}}return c}
function renderTextCanvas(layer,w,h){const c=makeCanvas(w,h),ctx=c.getContext('2d'),t={...defaultTextStyle(),...layer.text};ctx.save();ctx.fillStyle=t.color;ctx.textBaseline='top';ctx.textAlign=t.align;ctx.font=`${t.fontStyle} ${t.fontWeight} ${Math.max(4,t.fontSize)}px ${safeFont(t.fontFamily)}`;const lines=String(t.content??'').split('\n'),measure=line=>ctx.measureText(line).width+Math.max(0,line.length-1)*(t.letterSpacing||0),maxWidth=Math.max(1,...lines.map(measure)),x=t.align==='center'?maxWidth/2:t.align==='right'?maxWidth:0;let y=0;for(const line of lines){if(t.letterSpacing){drawSpacedText(ctx,line,x,y,t.letterSpacing,t.align)}else ctx.fillText(line,x,y);y+=t.fontSize*t.lineHeight}ctx.restore();return c}
function safeFont(font){return String(font||'system-ui').replace(/[;{}]/g,'')}
function drawSpacedText(ctx,text,x,y,spacing,align){const widths=[...text].map(ch=>ctx.measureText(ch).width),total=widths.reduce((a,b)=>a+b,0)+Math.max(0,text.length-1)*spacing;let px=align==='center'?x-total/2:align==='right'?x-total:x;const prev=ctx.textAlign;ctx.textAlign='left';[...text].forEach((ch,i)=>{ctx.fillText(ch,px,y);px+=widths[i]+spacing});ctx.textAlign=prev}
function tintCanvas(src,color){const c=makeCanvas(src.width,src.height),ctx=c.getContext('2d');ctx.drawImage(src,0,0);ctx.globalCompositeOperation='source-in';ctx.fillStyle=color;ctx.fillRect(0,0,c.width,c.height);return c}
function applyLayerEffects(src,fx,w,h){const f={...defaultLayerFx(),...fx};if(!f.enabled||(!f.shadow&&!f.glow&&!f.stroke))return src;const out=makeCanvas(w,h),ctx=out.getContext('2d');if(f.shadow){ctx.save();ctx.globalAlpha=f.shadowOpacity;ctx.shadowColor=f.shadowColor;ctx.shadowBlur=f.shadowBlur;ctx.shadowOffsetX=f.shadowX;ctx.shadowOffsetY=f.shadowY;ctx.drawImage(tintCanvas(src,f.shadowColor),0,0);ctx.restore()}if(f.glow){ctx.save();ctx.globalAlpha=f.glowOpacity;ctx.shadowColor=f.glowColor;ctx.shadowBlur=f.glowBlur;ctx.drawImage(tintCanvas(src,f.glowColor),0,0);ctx.restore()}if(f.stroke&&f.strokeSize>0){const colored=tintCanvas(src,f.strokeColor),s=Math.max(1,Math.round(f.strokeSize));ctx.save();for(let y=-s;y<=s;y++)for(let x=-s;x<=s;x++)if(x*x+y*y<=s*s)ctx.drawImage(colored,x,y);ctx.restore()}ctx.drawImage(src,0,0);return out}

export function drawLayerTransformed(ctx,canvas,layer,w,h){if(!canvas)return;ctx.save();ctx.translate(w/2+(layer.x||0),h/2+(layer.y||0));ctx.rotate(layer.rotation||0);ctx.scale(layer.scaleX||1,layer.scaleY||1);ctx.translate(-w/2,-h/2);ctx.drawImage(canvas,0,0);ctx.restore()}
export function layerPointFromDocument(point,layer,w,h){let x=point.x-(w/2+(layer.x||0)),y=point.y-(h/2+(layer.y||0));const r=-(layer.rotation||0),cr=Math.cos(r),sr=Math.sin(r),rx=x*cr-y*sr,ry=x*sr+y*cr;return{x:rx/(layer.scaleX||1)+w/2,y:ry/(layer.scaleY||1)+h/2}}
export function documentPointFromLayer(point,layer,w,h){let x=(point.x-w/2)*(layer.scaleX||1),y=(point.y-h/2)*(layer.scaleY||1);const r=layer.rotation||0,cr=Math.cos(r),sr=Math.sin(r);return{x:x*cr-y*sr+w/2+(layer.x||0),y:x*sr+y*cr+h/2+(layer.y||0)}}
export function getAlphaBounds(canvas){if(!canvas)return null;const ctx=canvas.getContext('2d',{willReadFrequently:true}),{width:w,height:h}=canvas,data=ctx.getImageData(0,0,w,h).data;let minX=w,minY=h,maxX=-1,maxY=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++){if(data[(y*w+x)*4+3]>5){if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y}}return maxX<0?null:{x:minX,y:minY,w:maxX-minX+1,h:maxY-minY+1}}
export function transformedBounds(layer,w,h,doc=null){if(!layer||layer.type==='group'||layer.type==='adjustment')return null;let source=layer.canvas;if(['text','shape'].includes(layer.type)&&doc)source=doc.renderLayerThumbnail(layer,256,256);const b=layer.type==='tiled'?{x:0,y:0,w,h}:(source?getAlphaBounds(source):null)||{x:0,y:0,w,h},pts=[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h}].map(p=>documentPointFromLayer(p,layer,w,h));return{points:pts,center:documentPointFromLayer({x:b.x+b.w/2,y:b.y+b.h/2},layer,w,h),local:b}}

export function adjustmentFilter({brightness=0,contrast=0,saturation=0}={}){return `brightness(${Math.max(0,100+(Number(brightness)||0))}%) contrast(${Math.max(0,100+(Number(contrast)||0))}%) saturate(${Math.max(0,100+(Number(saturation)||0))}%)`}
export function canvasToDataURL(canvas,type='image/png',quality=.92){return Promise.resolve(canvas.toDataURL(type,quality))}
export function drawDataURL(canvas,url){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{canvas.getContext('2d').drawImage(img,0,0);resolve()};img.onerror=reject;img.src=url})}
export async function imageFileToCanvas(file){try{if('createImageBitmap'in window){const bitmap=await createImageBitmap(file);const c=makeCanvas(bitmap.width,bitmap.height);c.getContext('2d').drawImage(bitmap,0,0);bitmap.close?.();return c}}catch{}const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=makeCanvas(img.naturalWidth,img.naturalHeight);c.getContext('2d').drawImage(img,0,0);resolve(c)};img.onerror=reject;img.src=url})}finally{URL.revokeObjectURL(url)}}
export async function imageFileToTiles(file,tileSize=512){const bmp=await createImageBitmap(file),tiles=[];try{for(let y=0;y<bmp.height;y+=tileSize)for(let x=0;x<bmp.width;x+=tileSize){const w=Math.min(tileSize,bmp.width-x),h=Math.min(tileSize,bmp.height-y),c=makeCanvas(w,h);c.getContext('2d').drawImage(bmp,x,y,w,h,0,0,w,h);tiles.push({x,y,w,h,canvas:c})}return{tileSize,width:bmp.width,height:bmp.height,tiles}}finally{bmp.close?.()}}

export class HistoryManager{constructor(limit=32){this.limit=limit;this.undoStack=[];this.redoStack=[];this.suspended=false}async push(doc,label='Cambio'){if(this.suspended)return;const snap=await doc.snapshot();this.undoStack.push({label,snap,at:Date.now()});if(this.undoStack.length>this.limit)this.undoStack.shift();this.redoStack=[]}async undo(){if(this.undoStack.length<=1)return null;const cur=this.undoStack.pop();this.redoStack.push(cur);return PixelDocument.fromSnapshot(this.undoStack.at(-1).snap)}async redo(){if(!this.redoStack.length)return null;const next=this.redoStack.pop();this.undoStack.push(next);return PixelDocument.fromSnapshot(next.snap)}async reset(doc){this.undoStack=[];this.redoStack=[];await this.push(doc,'Inicio')}entries(){return this.undoStack.map((e,i)=>({label:e.label,at:e.at,current:i===this.undoStack.length-1}))}}

function normalizeCurve(curve){const fallback=[0,64,128,192,255];if(!Array.isArray(curve)||curve.length!==5)return fallback;return curve.map((v,i)=>clamp(Number.isFinite(Number(v))?Number(v):fallback[i],0,255))}
function curveValue(v,curve){const c=normalizeCurve(curve),x=clamp(v,0,255),seg=Math.min(3,Math.floor(x/64)),x0=seg*64,x1=seg===3?255:(seg+1)*64,t=(x-x0)/(x1-x0||1);return c[seg]+(c[seg+1]-c[seg])*t}
function levelValue(v,black=0,gamma=1,white=255){const b=clamp(Number(black)||0,0,254),w=clamp(Number(white)||255,b+1,255),g=clamp(Number(gamma)||1,.1,5),n=clamp((v-b)/(w-b),0,1);return 255*Math.pow(n,1/g)}
export function applyToneControls(canvas,opts={},selection=null){const {blackPoint=0,gamma=1,whitePoint=255}=opts,curves=normalizeCurves(opts.curves,opts.curve),ctx=canvas.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,canvas.width,canvas.height),d=img.data,original=selection?new Uint8ClampedArray(d):null;for(let i=0,p=0;i<d.length;i+=4,p++){const mix=selection?selection[p]/255:1;if(!mix)continue;for(let c=0;c<3;c++){let v=levelValue(d[i+c],blackPoint,gamma,whitePoint);v=curveValue(v,curves.rgb);v=curveValue(v,[curves.r,curves.g,curves.b][c]);d[i+c]=original?original[i+c]+(v-original[i+c])*mix:v}}ctx.putImageData(img,0,0);return canvas}
export function applyAdjustments(canvas,opts={},selection=null){const {brightness=0,contrast=0,saturation=0,blackPoint=0,gamma=1,whitePoint=255}=opts,curves=normalizeCurves(opts.curves,opts.curve),ctx=canvas.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,canvas.width,canvas.height),d=img.data,original=new Uint8ClampedArray(d),bv=Number(brightness)*2.55,cv=(259*(Number(contrast)+255))/(255*(259-Number(contrast))),sat=(Number(saturation)+100)/100;for(let i=0,p=0;i<d.length;i+=4,p++){const mix=selection?selection[p]/255:1;if(!mix)continue;let r=d[i]+bv,g=d[i+1]+bv,b=d[i+2]+bv;r=cv*(r-128)+128;g=cv*(g-128)+128;b=cv*(b-128)+128;const gray=.299*r+.587*g+.114*b;r=gray+(r-gray)*sat;g=gray+(g-gray)*sat;b=gray+(b-gray)*sat;const vals=[r,g,b];for(let c=0;c<3;c++){let v=levelValue(vals[c],blackPoint,gamma,whitePoint);v=curveValue(v,curves.rgb);v=curveValue(v,[curves.r,curves.g,curves.b][c]);d[i+c]=original[i+c]+(clamp(v,0,255)-original[i+c])*mix}}ctx.putImageData(img,0,0)}
export function applyFilter(canvas,type,selection=null){const original=cloneCanvas(canvas),filtered=cloneCanvas(canvas),ctx=filtered.getContext('2d',{willReadFrequently:true});if(type==='blur'){const temp=cloneCanvas(filtered);ctx.clearRect(0,0,filtered.width,filtered.height);ctx.filter='blur(4px)';ctx.drawImage(temp,0,0);ctx.filter='none'}else if(type==='pixelate'){const temp=makeCanvas(1,1),scale=Math.max(1,Math.floor(Math.min(filtered.width,filtered.height)/80));temp.width=Math.max(1,Math.floor(filtered.width/scale));temp.height=Math.max(1,Math.floor(filtered.height/scale));const t=temp.getContext('2d');t.imageSmoothingEnabled=false;t.drawImage(filtered,0,0,temp.width,temp.height);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,filtered.width,filtered.height);ctx.drawImage(temp,0,0,temp.width,temp.height,0,0,filtered.width,filtered.height);ctx.imageSmoothingEnabled=true}else{const img=ctx.getImageData(0,0,filtered.width,filtered.height),d=img.data;if(type==='sharpen')sharpen(ctx,img,filtered.width,filtered.height);else if(type==='denoise')denoise(ctx,img,filtered.width,filtered.height);else{for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2];if(type==='grayscale'){const v=.299*r+.587*g+.114*b;d[i]=d[i+1]=d[i+2]=v}else if(type==='sepia'){d[i]=clamp(.393*r+.769*g+.189*b,0,255);d[i+1]=clamp(.349*r+.686*g+.168*b,0,255);d[i+2]=clamp(.272*r+.534*g+.131*b,0,255)}else if(type==='invert'){d[i]=255-r;d[i+1]=255-g;d[i+2]=255-b}}ctx.putImageData(img,0,0)}}if(!selection){canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);canvas.getContext('2d').drawImage(filtered,0,0);return}const out=canvas.getContext('2d',{willReadFrequently:true}),a=original.getContext('2d').getImageData(0,0,canvas.width,canvas.height),b=filtered.getContext('2d').getImageData(0,0,canvas.width,canvas.height),d=a.data;for(let i=0,p=0;i<d.length;i+=4,p++){const mix=selection[p]/255;if(!mix)continue;for(let c=0;c<4;c++)d[i+c]=d[i+c]+(b.data[i+c]-d[i+c])*mix}out.putImageData(a,0,0)}
function sharpen(ctx,img,w,h){const src=img.data,out=new Uint8ClampedArray(src),k=[0,-1,0,-1,5,-1,0,-1,0];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){for(let c=0;c<3;c++){let sum=0,ki=0;for(let ky=-1;ky<=1;ky++)for(let kx=-1;kx<=1;kx++)sum+=src[((y+ky)*w+(x+kx))*4+c]*k[ki++];out[(y*w+x)*4+c]=clamp(sum,0,255)}}ctx.putImageData(new ImageData(out,w,h),0,0)}
function denoise(ctx,img,w,h){const src=img.data,out=new Uint8ClampedArray(src);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=(y*w+x)*4,l=p-4,r=p+4,u=p-w*4,d=p+w*4;for(let c=0;c<3;c++)out[p+c]=(src[p+c]*4+src[l+c]+src[r+c]+src[u+c]+src[d+c])/8}ctx.putImageData(new ImageData(out,w,h),0,0)}
export function calculateHistogram(canvas,bins=256){const data=canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,canvas.width,canvas.height).data,r=new Uint32Array(bins),g=new Uint32Array(bins),b=new Uint32Array(bins),luma=new Uint32Array(bins),scale=(bins-1)/255;for(let i=0;i<data.length;i+=4){if(data[i+3]===0)continue;const ri=Math.round(data[i]*scale),gi=Math.round(data[i+1]*scale),bi=Math.round(data[i+2]*scale),li=Math.round((.299*data[i]+.587*data[i+1]+.114*data[i+2])*scale);r[ri]++;g[gi]++;b[bi]++;luma[li]++}return{r,g,b,luma,max:Math.max(1,...luma)}}
export function featherSelectionMask(mask,w,h,radius=0){const r=clamp(Math.round(Number(radius)||0),0,80);if(!r)return new Uint8Array(mask);const src=makeCanvas(w,h),sctx=src.getContext('2d'),img=sctx.createImageData(w,h);for(let p=0,i=0;p<mask.length;p++,i+=4){img.data[i]=img.data[i+1]=img.data[i+2]=255;img.data[i+3]=mask[p]}sctx.putImageData(img,0,0);const out=makeCanvas(w,h),octx=out.getContext('2d');octx.filter=`blur(${r}px)`;octx.drawImage(src,0,0);octx.filter='none';const d=octx.getImageData(0,0,w,h).data,result=new Uint8Array(w*h);for(let p=0,i=3;p<result.length;p++,i+=4)result[p]=d[i];return result}
export function createBackgroundRemovalMask(canvas,{tolerance=28,feather=2}={}){const w=canvas.width,h=canvas.height,ctx=canvas.getContext('2d',{willReadFrequently:true}),data=ctx.getImageData(0,0,w,h).data,total=w*h,visited=new Uint8Array(total),background=new Uint8Array(total),queue=new Int32Array(total);let head=0,tail=0;const sample=[],sx=Math.max(1,Math.floor(w/32)),sy=Math.max(1,Math.floor(h/32));for(let x=0;x<w;x+=sx){sample.push(x,(h-1)*w+x)}for(let y=0;y<h;y+=sy){sample.push(y*w,y*w+w-1)}let rr=0,gg=0,bb=0,aa=0,n=0;for(const p of sample){const i=p*4;if(data[i+3]<8)continue;rr+=data[i];gg+=data[i+1];bb+=data[i+2];aa+=data[i+3];n++}const ref=n?[rr/n,gg/n,bb/n,aa/n]:[255,255,255,255],maxDist=18+clamp(Number(tolerance)||0,0,100)*3.8,neighborLimit=Math.max(20,maxDist*.42),distRef=p=>{const i=p*4;return Math.hypot(data[i]-ref[0],data[i+1]-ref[1],data[i+2]-ref[2],(data[i+3]-ref[3])*.25)},distPair=(a,b)=>{const i=a*4,j=b*4;return Math.hypot(data[i]-data[j],data[i+1]-data[j+1],data[i+2]-data[j+2])},seed=p=>{if(visited[p])return;visited[p]=1;if(data[p*4+3]<8||distRef(p)<=maxDist){background[p]=1;queue[tail++]=p}};for(let x=0;x<w;x++){seed(x);seed((h-1)*w+x)}for(let y=0;y<h;y++){seed(y*w);seed(y*w+w-1)}while(head<tail){const p=queue[head++],x=p%w,y=Math.floor(p/w),neighbors=[];if(x>0)neighbors.push(p-1);if(x<w-1)neighbors.push(p+1);if(y>0)neighbors.push(p-w);if(y<h-1)neighbors.push(p+w);for(const q of neighbors){if(visited[q])continue;visited[q]=1;if(data[q*4+3]<8||(distRef(q)<=maxDist*1.35&&distPair(p,q)<=neighborLimit)){background[q]=1;queue[tail++]=q}}}const mask=new Uint8Array(total);for(let p=0;p<total;p++)mask[p]=background[p]?0:255;const softened=featherSelectionMask(mask,w,h,feather),out=makeCanvas(w,h),octx=out.getContext('2d'),img=octx.createImageData(w,h);for(let p=0,i=0;p<softened.length;p++,i+=4){img.data[i]=img.data[i+1]=img.data[i+2]=255;img.data[i+3]=softened[p]}octx.putImageData(img,0,0);return out}


export function warpCanvasMesh(source,mesh,outW=source.width,outH=source.height){
  const cols=Math.max(2,Math.round(mesh?.cols||3)),rows=Math.max(2,Math.round(mesh?.rows||3)),pts=mesh?.points;
  if(!Array.isArray(pts)||pts.length!==cols*rows)return cloneCanvas(source);
  const out=makeCanvas(outW,outH),ctx=out.getContext('2d');
  function tri(s0,s1,s2,d0,d1,d2){const den=s0.x*(s1.y-s2.y)+s1.x*(s2.y-s0.y)+s2.x*(s0.y-s1.y);if(Math.abs(den)<1e-8)return;const a=(d0.x*(s1.y-s2.y)+d1.x*(s2.y-s0.y)+d2.x*(s0.y-s1.y))/den,b=(d0.y*(s1.y-s2.y)+d1.y*(s2.y-s0.y)+d2.y*(s0.y-s1.y))/den,c=(d0.x*(s2.x-s1.x)+d1.x*(s0.x-s2.x)+d2.x*(s1.x-s0.x))/den,d=(d0.y*(s2.x-s1.x)+d1.y*(s0.x-s2.x)+d2.y*(s1.x-s0.x))/den,e=(d0.x*(s1.x*s2.y-s2.x*s1.y)+d1.x*(s2.x*s0.y-s0.x*s2.y)+d2.x*(s0.x*s1.y-s1.x*s0.y))/den,f=(d0.y*(s1.x*s2.y-s2.x*s1.y)+d1.y*(s2.x*s0.y-s0.x*s2.y)+d2.y*(s0.x*s1.y-s1.x*s0.y))/den;ctx.save();ctx.beginPath();ctx.moveTo(d0.x,d0.y);ctx.lineTo(d1.x,d1.y);ctx.lineTo(d2.x,d2.y);ctx.closePath();ctx.clip();ctx.setTransform(a,b,c,d,e,f);ctx.drawImage(source,0,0);ctx.restore()}
  const idx=(x,y)=>y*cols+x;
  for(let y=0;y<rows-1;y++)for(let x=0;x<cols-1;x++){
    const sx0=x/(cols-1)*source.width,sx1=(x+1)/(cols-1)*source.width,sy0=y/(rows-1)*source.height,sy1=(y+1)/(rows-1)*source.height;
    const s00={x:sx0,y:sy0},s10={x:sx1,y:sy0},s11={x:sx1,y:sy1},s01={x:sx0,y:sy1};
    const d00=pts[idx(x,y)],d10=pts[idx(x+1,y)],d11=pts[idx(x+1,y+1)],d01=pts[idx(x,y+1)];
    tri(s00,s10,s11,d00,d10,d11);tri(s00,s11,s01,d00,d11,d01);
  }
  ctx.setTransform(1,0,0,1,0,0);return out;
}
export function warpCanvasToQuad(source,quad,outW=source.width,outH=source.height,grid=18){const out=makeCanvas(outW,outH),ctx=out.getContext('2d'),q=(quad&&quad.length===4)?quad:identityWarp(source.width,source.height),lerp=(a,b,t)=>a+(b-a)*t,bilerp=(u,v)=>({x:lerp(lerp(q[0].x,q[1].x,u),lerp(q[3].x,q[2].x,u),v),y:lerp(lerp(q[0].y,q[1].y,u),lerp(q[3].y,q[2].y,u),v)});function tri(s0,s1,s2,d0,d1,d2){const den=s0.x*(s1.y-s2.y)+s1.x*(s2.y-s0.y)+s2.x*(s0.y-s1.y);if(Math.abs(den)<1e-8)return;const a=(d0.x*(s1.y-s2.y)+d1.x*(s2.y-s0.y)+d2.x*(s0.y-s1.y))/den,b=(d0.y*(s1.y-s2.y)+d1.y*(s2.y-s0.y)+d2.y*(s0.y-s1.y))/den,c=(d0.x*(s2.x-s1.x)+d1.x*(s0.x-s2.x)+d2.x*(s1.x-s0.x))/den,d=(d0.y*(s2.x-s1.x)+d1.y*(s0.x-s2.x)+d2.y*(s1.x-s0.x))/den,e=(d0.x*(s1.x*s2.y-s2.x*s1.y)+d1.x*(s2.x*s0.y-s0.x*s2.y)+d2.x*(s0.x*s1.y-s1.x*s0.y))/den,f=(d0.y*(s1.x*s2.y-s2.x*s1.y)+d1.y*(s2.x*s0.y-s0.x*s2.y)+d2.y*(s0.x*s1.y-s1.x*s0.y))/den;ctx.save();ctx.beginPath();ctx.moveTo(d0.x,d0.y);ctx.lineTo(d1.x,d1.y);ctx.lineTo(d2.x,d2.y);ctx.closePath();ctx.clip();ctx.setTransform(a,b,c,d,e,f);ctx.drawImage(source,0,0);ctx.restore()}for(let gy=0;gy<grid;gy++)for(let gx=0;gx<grid;gx++){const u0=gx/grid,u1=(gx+1)/grid,v0=gy/grid,v1=(gy+1)/grid,s00={x:u0*source.width,y:v0*source.height},s10={x:u1*source.width,y:v0*source.height},s11={x:u1*source.width,y:v1*source.height},s01={x:u0*source.width,y:v1*source.height},d00=bilerp(u0,v0),d10=bilerp(u1,v0),d11=bilerp(u1,v1),d01=bilerp(u0,v1);tri(s00,s10,s11,d00,d10,d11);tri(s00,s11,s01,d00,d11,d01)}ctx.setTransform(1,0,0,1,0,0);return out}
export function cropCanvasRegion(canvas,x,y,w,h){const out=makeCanvas(Math.max(1,w),Math.max(1,h));out.getContext('2d').drawImage(canvas,x,y,w,h,0,0,w,h);return out}
export function cropTiledData(tiled,x,y,w,h){const tileSize=Math.max(64,Number(tiled?.tileSize)||512),out={tileSize,width:w,height:h,tiles:[]},src=tiled?.tiles||[];for(let oy=0;oy<h;oy+=tileSize)for(let ox=0;ox<w;ox+=tileSize){const tw=Math.min(tileSize,w-ox),th=Math.min(tileSize,h-oy),c=makeCanvas(tw,th),ctx=c.getContext('2d');let used=false;const sx0=x+ox,sy0=y+oy,sx1=sx0+tw,sy1=sy0+th;for(const t of src){const ix0=Math.max(sx0,t.x),iy0=Math.max(sy0,t.y),ix1=Math.min(sx1,t.x+t.w),iy1=Math.min(sy1,t.y+t.h);if(ix1<=ix0||iy1<=iy0||!t.canvas)continue;ctx.drawImage(t.canvas,ix0-t.x,iy0-t.y,ix1-ix0,iy1-iy0,ix0-sx0,iy0-sy0,ix1-ix0,iy1-iy0);used=true}if(used)out.tiles.push({x:ox,y:oy,w:tw,h:th,canvas:c})}return out}
export async function canvasToTiles(canvas,tileSize=512){const tiles=[];for(let y=0;y<canvas.height;y+=tileSize)for(let x=0;x<canvas.width;x+=tileSize){const w=Math.min(tileSize,canvas.width-x),h=Math.min(tileSize,canvas.height-y),c=makeCanvas(w,h);c.getContext('2d').drawImage(canvas,x,y,w,h,0,0,w,h);tiles.push({x,y,w,h,canvas:c})}return{tileSize,width:canvas.width,height:canvas.height,tiles}}
