const CACHE='pixelforge-404-v7.1-ux-a11y';
const CORE=['./','./index.html','./manifest.webmanifest','./models/pixelforge-neural-lite.json','./qa.html','./js/qa.js','./icons/icon.svg','./icons/icon-192.png','./icons/icon-512.png','./css/pf-v7.1.css','./js/pf-v7.1.js'];
const OPTIONAL=['./vendor/libraw/index.js','./vendor/libraw/worker.js','./vendor/libraw/libraw.js','./vendor/libraw/libraw.wasm'];
function isolated(resp){if(!resp||resp.type==='opaque')return resp;const h=new Headers(resp.headers);h.set('Cross-Origin-Opener-Policy','same-origin');h.set('Cross-Origin-Embedder-Policy','require-corp');h.set('Cross-Origin-Resource-Policy','same-origin');return new Response(resp.body,{status:resp.status,statusText:resp.statusText,headers:h})}
function decorateHtml(text){let html=String(text||'').replace(/PixelForge 404 v7\.0\.1 Final/g,'PixelForge 404 v7.1 UX/A11Y').replace(/v7\.0\.1 Final/g,'v7.1 UX/A11Y');if(!html.includes('css/pf-v7.1.css'))html=html.replace('</head>','  <link rel="stylesheet" href="css/pf-v7.1.css">\n</head>');if(!html.includes('js/pf-v7.1.js'))html=html.replace('</body>','  <script src="js/pf-v7.1.js" defer></script>\n</body>');return html}
async function decorateResponse(resp){if(!resp||!resp.ok)return resp;const type=resp.headers.get('content-type')||'';if(!type.includes('text/html'))return resp;const h=new Headers(resp.headers);h.delete('content-length');return new Response(decorateHtml(await resp.text()),{status:resp.status,statusText:resp.statusText,headers:h})}
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(CORE);try{const r=await fetch('./index.html',{cache:'no-store'});if(r.ok)await c.put('./index.html',await decorateResponse(r))}catch{}await Promise.allSettled(OPTIONAL.map(async u=>{const r=await fetch(u,{cache:'no-store'});if(r.ok)await c.put(u,r)}));await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);if(self.registration.navigationPreload)await self.registration.navigationPreload.enable();await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});await Promise.allSettled(clients.map(c=>c.navigate(c.url)))})()));
async function networkFirst(req,preload,fallbackToIndex=false){try{let r=(await preload)||await fetch(req);if(r?.ok){if(req.mode==='navigate'||/\.html?$/i.test(new URL(req.url).pathname))r=await decorateResponse(r);const copy=r.clone();void caches.open(CACHE).then(c=>c.put(req,copy));return isolated(r)}}catch{}let cached=await caches.match(req);if(!cached&&fallbackToIndex)cached=await caches.match('./index.html');return cached?isolated(cached):Response.error()}
async function cacheFirst(req){const cached=await caches.match(req);if(cached)return isolated(cached);try{const r=await fetch(req);if(r?.ok){const copy=r.clone();void caches.open(CACHE).then(c=>c.put(req,copy))}return isolated(r)}catch{return Response.error()}}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const url=new URL(e.request.url);if(url.origin!==self.location.origin)return;const codeLike=e.request.mode==='navigate'||['script','style','worker','sharedworker','manifest'].includes(e.request.destination)||/\.(?:js|css|html|json|webmanifest)$/i.test(url.pathname);e.respondWith(codeLike?networkFirst(e.request,e.preloadResponse,e.request.mode==='navigate'):cacheFirst(e.request))});
